<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.0
 */

/**
 * Database `guerrerosz`
 */

/* `guerrerosz`.`warriors` */
$warriors = array(
  array('id' => '1','first_name' => 'fray','last_name' => 'soto','birth_date' => '2024-05-07'),
  array('id' => '2','first_name' => 'fray','last_name' => 'soto','birth_date' => '2024-05-01'),
  array('id' => '3','first_name' => 'fray','last_name' => 'soto','birth_date' => '2024-05-07'),
  array('id' => '4','first_name' => 'fray','last_name' => 'soto','birth_date' => '2024-05-07'),
  array('id' => '5','first_name' => 'prue','last_name' => 'BA','birth_date' => '2024-05-10'),
  array('id' => '6','first_name' => 'TEST','last_name' => 'TE','birth_date' => '2024-05-01')
);